"""Stage D: one nonlinear solve of the 4D model configuration.

Two nonlinearities are resolved in a single outer loop:
  * unilateral contact between the aligner and the crowns/attachments, with
    Coulomb friction carried by a secant tangential stiffness;
  * the bilinear ('double linear stress-strain curve') PDL, applied as a secant
    modulus driven by the von Mises equivalent strain of each element.

Because D(E, nu) = E * Dhat(nu), the element operators B and V are built once per
configuration and only the per-element modulus is refreshed between iterations.
"""
import sys, os, time
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'ofj'))
from scipy.sparse import csr_matrix, coo_matrix, diags, triu
from scipy.sparse.linalg import cg
import pyamg
from fem import isotropic_D, shape_grads, B_matrix
from contact import build_pairs
import gpu4d
import spec

K_N = float(os.environ.get('OFJ_K_N', 2000.0))
# Tangential (friction) contact stiffness.  With the whole inner aligner surface
# referenced to a passive fit, a stiff tangential spring lets the appliance carry
# a large couple on the crown, which turns tipping into bodily movement -- so this
# is the knob that governs movement TYPE, not just the friction magnitude.
K_T = float(os.environ.get('OFJ_K_T', 2000.0))
# The aligner is generated by a rolling-ball closing on a voxel grid, so its inner
# surface sits a small distance outside the crowns everywhere.  That standoff is a
# meshing artefact, not clearance: a thermoformed appliance is in contact.  It is
# removed per contact pair by referencing every gap to the UNSTAGED configuration,
# so a step-0 aligner on unmoved teeth is exactly passive and the only thing that
# loads the dentition is the staged interference.  MAX_GAP is deliberately large so
# no pair is ever dropped and pair i always means slave node i.
MAX_GAP = 6.0
# Thermoforming fit tolerance.  The reference above makes the appliance a perfect
# glove: every slave node sits at exactly zero gap, so the shell resists the crown
# ROTATING as well as translating.  A real appliance has some slack.  Diagnostic
# knob (mm) for how much of the movement-type discrepancy that assumption causes.
# Too much of it and the appliance loses its grip: the aligner is held only by
# contact with the crowns, so once enough pairs go inactive it keeps a rigid-body
# freedom and the reduced system is singular (PARDISO reports a zero pivot).
# 0.03 mm is seated; 0.06 mm is not.
CLEARANCE = float(os.environ.get('OFJ_CLEARANCE', 0.0))
MAXIT = int(os.environ.get('OFJ_MAXIT', 35))
RELAX = float(os.environ.get('OFJ_RELAX', 0.5))
U_TOL = 1e-3
F_TOL = 5e-3
RTOL = 1e-6
CG_MAX = 400          # hard cap; the hierarchy is rebuilt instead of grinding
AMG_EVERY = int(os.environ.get('OFJ_AMG_EVERY', 1))
# Linear backend: 'auto' uses cuDSS on the GPU when its libraries are installed at
# OFJ_CUDSS_DIR, else PARDISO when MKL is importable, else AMG+CG.
LINSOLVE = os.environ.get('OFJ_LINSOLVE', 'auto').lower()



def vm_equiv_strain(eps):
    """von Mises equivalent strain from Voigt strain with engineering shears."""
    ex, ey, ez, gxy, gyz, gzx = eps.T
    tr = (ex+ey+ez)/3.0
    dx, dy, dz = ex-tr, ey-tr, ez-tr
    ee = dx*dx + dy*dy + dz*dz + 0.5*(gxy*gxy + gyz*gyz + gzx*gzx)
    return np.sqrt(np.maximum(2.0/3.0*ee, 0.0))


def pdl_secant_modulus(eps_eq):
    """Secant modulus of the bilinear curve
       sigma = E1*e                        e <= ek
       sigma = E1*ek + E2*(e-ek)           e >  ek
    """
    E1, E2, ek = spec.PDL_E1, spec.PDL_E2, spec.PDL_EPS_KNEE
    e = np.maximum(eps_eq, 1e-12)
    return np.where(e <= ek, E1, (E1*ek + E2*(e-ek))/e)


class Operators:
    """Element operators for one configuration (rebuilt when nodes move).

    With `reuse=True` the COO -> CSR mapping is built once and the per-iteration
    assembly becomes a scatter-add into a fixed pattern.  Only the per-element
    modulus changes between nonlinear iterations, so re-sorting 24M COO entries
    every time was ~4x the cost of the assembly itself.  Exact: the pattern is
    identical and values differ only by summation order (~1e-16 relative).
    """

    def __init__(self, nodes, tets, nu, reuse=False):
        G, V = shape_grads(nodes, tets)
        neg = V <= 0
        if neg.any():
            tets = tets.copy(); tets[neg] = tets[neg][:, [0, 1, 3, 2]]
            G, V = shape_grads(nodes, tets)
        self.tets = tets
        self.B = B_matrix(G)
        self.V = V
        self.Dhat = isotropic_D(1.0, nu)
        BD = np.einsum('nki,kl->nli', self.B, self.Dhat)          # Dhat B
        self.Ke_unit = np.einsum('nli,nlj->nij', BD, self.B)*V[:, None, None]
        del BD
        d = (3*tets[:, :, None] + np.arange(3)[None, None, :]).reshape(len(tets), 12)
        self.dofs = d
        self.rows = np.repeat(d, 12, axis=1).ravel().astype(np.int32)
        self.cols = np.tile(d, (1, 12)).ravel().astype(np.int32)
        self.reuse = reuse
        self._csr = None

    def _build_map(self, ndof):
        """Fixed CSR pattern + the COO -> CSR index map (~1.9 s for the PDL,
        amortised over the ~30 iterations of a solve)."""
        keys = self.rows.astype(np.int64)*ndof + self.cols
        uk, inv = np.unique(keys, return_inverse=True)
        del keys
        rows_u = (uk // ndof).astype(np.int32)
        cols_u = (uk % ndof).astype(np.int32)
        indptr = np.zeros(ndof+1, dtype=np.int64)
        np.cumsum(np.bincount(rows_u, minlength=ndof), out=indptr[1:])
        self._csr = (inv.astype(np.int32), cols_u, indptr, len(uk), ndof)

    def K(self, E, ndof):
        vals = (self.Ke_unit*np.asarray(E)[:, None, None]).ravel()
        if not self.reuse:
            return coo_matrix((vals, (self.rows, self.cols)),
                              shape=(ndof, ndof)).tocsr()
        if self._csr is None or self._csr[4] != ndof:
            self._build_map(ndof)
        inv, cols_u, indptr, nnz, _ = self._csr
        data = np.bincount(inv, weights=vals, minlength=nnz)
        return csr_matrix((data, cols_u, indptr), shape=(ndof, ndof))

    def strain(self, u):
        ue = u.reshape(-1, 3)[self.tets].reshape(len(self.tets), 12)
        return np.einsum('nij,nj->ni', self.B, ue)


def contact_ops(C):
    s, tri, w, n = C['slave'], C['tri'], C['bary'], C['normal']
    npair = len(s)
    dofs = np.concatenate(
        [3*s[:, None] + np.arange(3)[None, :],
         (3*tri[:, :, None] + np.arange(3)[None, None, :]).reshape(npair, 9)], axis=1)
    R = np.zeros((npair, 3, 12))
    for d in range(3):
        R[:, d, d] = 1.0
        for j in range(3):
            R[:, d, 3+3*j+d] = -w[:, j]
    a = np.einsum('nij,ni->nj', R, n)
    return dofs, R, a


def make_amg(A, B=None):
    """Energy-smoothed aggregation, falling back to cheaper setups under memory
    pressure -- an 8 h staging run must not die on one transient allocation."""
    import gc
    for smooth, coarse in (('energy', 1500), ('jacobi', 3000), (None, 6000)):
        try:
            return _amg(A, B, smooth, coarse)
        except (MemoryError, np.core._exceptions._ArrayMemoryError):
            gc.collect()
            print(f"    [amg] memory pressure -> falling back "
                  f"(smooth={smooth} failed)", flush=True)
    raise MemoryError('AMG setup failed at every fallback level')


def _amg(A, B, smooth, max_coarse):
    return pyamg.smoothed_aggregation_solver(
        A, B=B, max_coarse=max_coarse, smooth=smooth,
        strength=('symmetric', {'theta': 0.02}),
        presmoother=('gauss_seidel', {'sweep': 'symmetric', 'iterations': 2}),
        postsmoother=('gauss_seidel', {'sweep': 'symmetric', 'iterations': 2}))


class Pardiso:
    """MKL PARDISO on the reduced system, mtype 2 (real symmetric positive definite).

    The AMG hierarchy has to be rebuilt every iteration because the contact springs
    move the spectrum, and that setup is ~75% of the wall time.  A sparse direct
    factorisation has no such problem: the reduced system is SPD, 150k dof and only
    5.7M nnz, and the fill-in is modest (25M nnz in the factor, ~230 MB).

    PARDISO splits into three phases, and only the first depends on the VALUES not
    at all:
        11  symbolic analysis (fill-reducing ordering)   ~0.59 s -- pattern only
        22  numeric factorisation                        ~0.20 s
        33  back-substitution                            ~0.07 s
    The pattern changes only when the contact active set changes, so the analysis is
    kept and reused whenever the incoming pattern is unchanged (phases 22+33 alone).
    That is exact -- no tolerance, no stale-preconditioner risk, which is what made
    every AMG reuse scheme fail here.

    Only the upper triangle is passed, as mtype 2 requires.
    """

    name = 'pardiso'
    ANALYSIS, FACTORISE, SOLVE, REFACTORISE, FREE = 11, 22, 33, 23, -1

    def __init__(self):
        from pypardiso import PyPardisoSolver
        self.ps = PyPardisoSolver(mtype=2)
        self._ptr = None
        self._ind = None
        self.n_analysis = 0
        self.n_reuse = 0

    @staticmethod
    def available():
        if LINSOLVE == 'amg':
            return False
        try:
            import pypardiso                                   # noqa: F401
            return True
        except Exception as e:
            if LINSOLVE == 'pardiso':
                raise RuntimeError(f'OFJ_LINSOLVE=pardiso but pypardiso is unusable: {e}')
            return False

    def _phase(self, ph, U, b):
        self.ps.set_phase(ph)
        return self.ps._call_pardiso(U, b)

    def solve(self, As, bs, upper=False):
        """Returns (x, reused) for the SPD system As x = bs.

        `upper=True` says As is already the upper triangle.  The GPU assembler
        hands one over directly, in index arrays it reuses between iterations, so
        the pattern check below succeeds on identity and costs nothing.
        """
        U = As if upper else triu(As, format='csr')
        if not upper:
            U.sort_indices()
            if U.dtype != np.float64:
                U = U.astype(np.float64)
        b = np.ascontiguousarray(bs, dtype=np.float64)
        self.ps._check_A(U)
        reused = self._ptr is not None and (
            (self._ptr is U.indptr and self._ind is U.indices)
            or (len(self._ptr) == len(U.indptr)
                and len(self._ind) == len(U.indices)
                and np.array_equal(self._ptr, U.indptr)
                and np.array_equal(self._ind, U.indices)))
        try:
            if reused:
                x = self._phase(self.REFACTORISE, U, b)        # 22 + 33
                self.n_reuse += 1
            else:
                self._phase(self.ANALYSIS, U, b)
                self._phase(self.FACTORISE, U, b)
                x = self._phase(self.SOLVE, U, b)
                self._ptr, self._ind = U.indptr, U.indices
                self.n_analysis += 1
        except Exception:
            # a failed phase leaves the handle in an undefined state; drop it and
            # redo the analysis from scratch before giving up on the backend
            self.free()
            self.ps._check_A(U)
            self._phase(self.ANALYSIS, U, b)
            self._phase(self.FACTORISE, U, b)
            x = self._phase(self.SOLVE, U, b)
            self._ptr, self._ind = U.indptr, U.indices
            self.n_analysis += 1
            reused = False
        return x, reused

    def free(self):
        try:
            self.ps.free_memory(everything=True)
        except Exception:
            pass
        self._ptr = self._ind = None


# NVIDIA cuDSS, loaded from an isolated directory so the model's torch keeps its own
# CUDA libraries (a Studio cannot hold a second environment).
CUDSS_DIR = os.environ.get('OFJ_CUDSS_DIR', os.path.expanduser('~/.pylibs_cudss'))


class CuDSS:
    """NVIDIA cuDSS sparse direct solver on the GPU (via nvmath-python), SPD, upper.

    Measured on the 2-core host with a Tesla T4, refactorisation + solve per
    nonlinear iteration:
        rigid bone        150,644 dof    PARDISO 0.69 s    cuDSS 0.12 s
        deformable bone   304,499 dof    PARDISO 5.66 s    cuDSS 0.89 s
    with residuals ~1e-15.  PARDISO was the right call on a 4-core host with the
    rigid model; with 2 cores and the bone meshed, the factorisation is where the
    time goes, and it is dense supernodal BLAS3 -- which the T4 does in float64
    faster than two host cores.

    libcudss is preloaded by absolute path AFTER torch is imported, so it binds to
    torch's already-loaded cuBLAS instead of the newer copy beside it (verified: one
    cuBLAS mapped, torch GPU ops unaffected).  The symbolic analysis is kept while
    the sparsity pattern is unchanged, exactly as for PARDISO.
    """

    name = 'cudss'

    def __init__(self):
        import ctypes
        import torch                                           # noqa: F401  CUDA libs first
        lib = os.path.join(CUDSS_DIR, 'nvidia', 'cu12', 'lib')
        ctypes.CDLL(os.path.join(lib, 'libcudss.so.0'), mode=ctypes.RTLD_GLOBAL)
        if CUDSS_DIR not in sys.path:
            sys.path.append(CUDSS_DIR)
        from nvmath.sparse import advanced as adv
        self.adv = adv
        kw = dict(sparse_system_type=adv.DirectSolverMatrixType.SPD,
                  sparse_system_view=adv.DirectSolverMatrixViewType.UPPER)
        mt = os.path.join(lib, 'libcudss_mtlayer_gomp.so.0')
        if os.path.exists(mt):
            kw['multithreading_lib'] = mt
        self.opts = adv.DirectSolverOptions(**kw)
        self.s = None
        self._ptr = self._ind = None
        self.n_analysis = 0
        self.n_reuse = 0

    @staticmethod
    def available():
        return (LINSOLVE in ('cudss', 'auto') and
                os.path.exists(os.path.join(CUDSS_DIR, 'nvidia', 'cu12', 'lib', 'libcudss.so.0')))

    def solve(self, As, bs, upper=False):
        U = As if upper else triu(As, format='csr')
        if not upper:
            U.sort_indices()
            if U.dtype != np.float64:
                U = U.astype(np.float64)
        b = np.ascontiguousarray(bs, dtype=np.float64)
        same = self.s is not None and (
            (self._ptr is U.indptr and self._ind is U.indices)
            or (len(self._ptr) == len(U.indptr) and len(self._ind) == len(U.indices)
                and np.array_equal(self._ptr, U.indptr)
                and np.array_equal(self._ind, U.indices)))
        if same:
            self.s.reset_operands(a=U, b=b)
            self.n_reuse += 1
        else:
            self.free()
            self.s = self.adv.DirectSolver(U, b, options=self.opts)
            self.s.plan()
            self._ptr, self._ind = U.indptr, U.indices
            self.n_analysis += 1
        self.s.factorize()
        return np.asarray(self.s.solve(), dtype=np.float64), same

    def free(self):
        if self.s is not None:
            try:
                self.s.free()
            except Exception:
                pass
        self.s = None
        self._ptr = self._ind = None


# Assemble on the GPU when there is one (OFJ_GPU=off disables it).  It needs the
# direct solver: the device assembler emits only the upper triangle, which AMG+CG
# cannot use.
USE_GPU = gpu4d.available() and Pardiso.available()


_DIRECT = None


def direct_solver():
    """Module-level singleton: the MKL handle and the kept symbolic factorisation
    have to survive across iterations and across the two solves of a staging step,
    which share a pairing and therefore often share a pattern."""
    global _DIRECT
    if _DIRECT is None:
        if CuDSS.available():
            try:
                _DIRECT = CuDSS()
            except Exception as e:
                if LINSOLVE == 'cudss':
                    raise
                print(f"    [linsolve] cuDSS unavailable ({type(e).__name__}: "
                      f"{str(e)[:60]}) -- using PARDISO", flush=True)
        if _DIRECT is None and Pardiso.available():
            _DIRECT = Pardiso()
    return _DIRECT


def solve_config(S, state, load, mu=spec.FRICTION, verbose=False, x0=None,
                 E_pdl0=None, maxit=MAXIT, cache=None, contact_ref=None):
    """Solve one configuration.  Returns dict with tooth rigid motions and fields."""
    nodes = state.nodes()
    for u in S.keep:
        S.tooth[u]['centroid_cur'] = state.centroid(u)
    P = S.build_P(nodes)
    ndof = 3*S.n_global

    opA = Operators(nodes, S.aligner_tets, spec.NU_ALIGNER)
    opP = Operators(nodes, S.pdl_tets, spec.PDL_NU, reuse=not USE_GPU)
    # deformable bone: its modulus is fixed per element, so like the aligner it is
    # assembled once per solve
    opB = (Operators(nodes, S.bone_tets, S.bone_nu)
           if getattr(S, 'deformable_bone', False) else None)

    def host_fixed_stiffness():
        K = opA.K(np.full(len(S.aligner_tets), spec.E_ALIGNER), ndof)
        if opB is not None:
            K = K + opB.K(S.bone_E, ndof)
        return (P.T @ K @ P).tocsr()

    if USE_GPU:
        KAr = None          # the device assembles the aligner term into the global
    else:                   # pattern instead of carrying a reduced copy
        KAr = host_fixed_stiffness()

    # per-element modulus scale: 1.0 everywhere unless OFJ_PDL_E_SCALE is set (see spec)
    pdl_scale = np.ones(len(S.pdl_tets))
    if spec.PDL_E_SCALE != 1.0:
        unns = [spec.UNN[int(f)] for f in spec.PDL_E_SCALE_FDI.split(',') if f.strip()]
        pdl_scale[np.isin(S.pdl_owner, unns)] = spec.PDL_E_SCALE

    E_pdl = (np.full(len(S.pdl_tets), spec.PDL_E1)*pdl_scale) if E_pdl0 is None else E_pdl0.copy()

    # ---- contact: pairing fixed for the whole step (small sliding) -------------
    # `contact_ref` carries the pairing and the manufactured standoff, both
    # evaluated in the configuration the aligner was made for.  Interference is
    # measured against THAT, so a tooth sitting at its prescribed position feels
    # exactly zero force and the load cannot accumulate with distance travelled.
    slave = contact_ref['slave']
    gap_now, nrm = S.gap_for_pairing(nodes, slave, contact_ref['tri'],
                                     contact_ref['bary'])
    C = dict(slave=slave, tri=contact_ref['tri'], bary=contact_ref['bary'],
             normal=nrm, gap0=gap_now)
    dofs, R, a = contact_ops(C)
    gref = gap_now - contact_ref['gap_pre'] + CLEARANCE
    npair = len(gref)
    pair_tooth = S.master_owner[
        np.searchsorted(np.arange(len(S.master_tris)), np.arange(npair))] \
        if False else None
    active = gref <= 0.0
    lam = np.zeros(npair); tmag_prev = np.zeros(npair)
    # The cached active set, lam and tmag are indexed BY PAIR, so they may only be
    # carried over while the pairing is the one they were computed against -- i.e.
    # between the two PDL iterations of a step, not across steps.  ~0.8% of slave
    # nodes re-pair to a different master triangle each step, and carrying their
    # contact state onto a different surface is the same inconsistency that
    # FINDINGS 2 records for the gap reference.  It seeds a limit cycle: the same
    # configuration solved cold converges (dA -> 0, 22 N) where the warm start
    # cycles between 15 N and 500 N and never converges.
    pairing = contact_ref['tri']
    if (cache is not None and cache.get('npair') == npair
            and cache.get('pairing') is pairing):
        active = cache['active'].copy()
        lam = cache['lam'].copy()
        tmag_prev = cache['tmag'].copy()
    Pt_all = np.eye(3)[None, :, :] - np.einsum('ni,nj->nij', nrm, nrm)

    fr_ext = P.T @ load.vector(S, state, ndof)
    if hasattr(load, 'reduced_vector'):
        # loads applied straight to a tooth's rigid dofs (a bonded metal hook)
        fr_ext = fr_ext + load.reduced_vector(S, state, S.n_red)
    Brm = S.rigid_modes(nodes)

    gsys = None
    if USE_GPU:
        try:
            # the pattern belongs to the step (the pairing is fixed for it), the
            # values to this solve
            gsys = gpu4d.for_step(contact_ref['tri'], ndof, dofs,
                                  opA.dofs, opP.dofs,
                                  bone_dofs=(opB.dofs if opB is not None else None))
            gsys.refresh(P, opA, opP, spec.E_ALIGNER, R, a, Pt_all, opB=opB,
                         E_bone=(S.bone_E if opB is not None else None))
        except Exception as e:
            print(f"    [gpu] assembly unavailable ({type(e).__name__}: "
                  f"{str(e)[:60]}) -- assembling on the host", flush=True)
            gsys = None
            KAr = host_fixed_stiffness()
            opP.reuse = True

    # tooth-tooth contact between adjacent crowns (contact4d.ToothContact), when enabled
    tc = getattr(S, 'tooth_contact', None)
    if tc is not None:
        tc.select(state.T)
        Ct = tc.rows(S, S.n_red, {u_: S.tooth[u_]['centroid_cur'] for u_ in S.keep})
        CtT = Ct.T.tocsr()
        dlt_t = np.zeros(Ct.shape[0])
    tc_same = True
    tcm = None

    direct = direct_solver()
    ml = None; rebuild = False; u = np.zeros(ndof)
    u_prev = None; Fc_prev = None; hist = []
    for it in range(maxit):
        # secant tangential stiffness, over every pair; the mask decides which of
        # them actually contributes
        ksec_all = np.where(K_T*tmag_prev <= mu*lam, K_T,
                            mu*lam/np.maximum(tmag_prev, 1e-12))
        ksec_all = np.clip(ksec_all, 0.0, K_T)
        upper = False
        if gsys is not None:
            # every pair is assembled every iteration, inactive ones as a genuine
            # zero, so the pattern is the step's and PARDISO keeps its analysis
            As, bs, dg = gsys.system(E_pdl, active, ksec_all, K_N, gref, fr_ext)
            upper = True
        else:
            KP = opP.K(E_pdl, ndof)
            Kr = KAr + (P.T @ KP @ P).tocsr()
            del KP
            act = np.where(active)[0]
            ksec = ksec_all[act]
            Kn = K_N*np.einsum('ni,nj->nij', a[act], a[act])
            Ke = Kn + ksec[:, None, None]*np.einsum('nki,nkl,nlj->nij',
                                                    R[act], Pt_all[act], R[act])
            d = dofs[act]
            Kc = coo_matrix((Ke.ravel(),
                             (np.repeat(d, 12, axis=1).ravel(), np.tile(d, (1, 12)).ravel())),
                            shape=(ndof, ndof)).tocsr()
            fc = np.zeros(ndof)
            np.add.at(fc, d.ravel(), ((-K_N*gref[act])[:, None]*a[act]).ravel())

            A = (Kr + (P.T @ Kc @ P)).tocsr()
            b = fr_ext + P.T @ fc
            # symmetric Jacobi scaling: the aligner/PDL modulus ratio is 30000:1
            dg = np.sqrt(A.diagonal()); dg[dg <= 0] = 1.0
            Di = diags(1.0/dg)
            As = (Di @ A @ Di).tocsr(); bs = b/dg
        if tc is not None:
            kt, ft = tc.law(dlt_t)
            kt = np.maximum(kt, 1e-12)                   # keep the pattern fixed within the step
            Kc = (CtT @ diags(kt) @ Ct).tocoo()          # small: rigid dofs of adjacent teeth only
            sel = (Kc.row <= Kc.col) if upper else slice(None)
            kr, kc = Kc.row[sel], Kc.col[sel]
            kv = Kc.data[sel]/(dg[kr]*dg[kc])
            # merge into the (huge) scaled system in place: the union pattern and the index maps
            # are built once per solve, then only values are copied (a sparse '+' per iteration
            # cost ~1 s at 150k dof)
            nA = As.shape[0]
            if tcm is None or tcm['ptr'] is not As.indptr:
                rA = np.repeat(np.arange(nA, dtype=np.int64), np.diff(As.indptr))
                keyA = rA*nA + As.indices
                keyK = np.unique(kr.astype(np.int64)*nA + kc)
                keyM = np.union1d(keyA, keyK)
                M = csr_matrix((np.zeros(len(keyM)), (keyM // nA, keyM % nA)), shape=As.shape)
                M.sort_indices()
                tcm = dict(ptr=As.indptr, M=M, mapA=np.searchsorted(keyM, keyA), keyM=keyM)
            M = tcm['M']
            M.data[:] = 0.0
            M.data[tcm['mapA']] = As.data
            np.add.at(M.data, np.searchsorted(tcm['keyM'], kr.astype(np.int64)*nA + kc), kv)
            As = M
            bs = bs - (CtT @ ft)/dg
        nit = [0]; t_setup = 0.0
        ts = time.time()
        if direct is not None:
            # Direct factorisation: exact, so there is no preconditioner to go
            # stale and no iteration count to watch.
            try:
                xs, reused = direct.solve(As, bs, upper=upper)
                # As may be the upper triangle alone; the symmetric product is
                # then U x + U^T x - diag(U) x
                r = bs - (As@xs + As.T@xs - As.diagonal()*xs if upper else As@xs)
                res = np.linalg.norm(r)/max(np.linalg.norm(bs), 1e-30)
                if not np.isfinite(res) or res > 1e-8:
                    raise RuntimeError(f'{direct.name} residual {res:.2e}')
                tag_lin = f"{direct.name}{' reuse' if reused else ''}"
            except Exception as e:
                if getattr(direct, 'name', '') == 'cudss' and Pardiso.available():
                    # the CPU direct solver, not AMG+CG: at 300k dof the AMG path
                    # would be two orders of magnitude slower
                    print(f"    [linsolve] cuDSS failed ({type(e).__name__}: "
                          f"{str(e)[:60]}) -- switching to PARDISO", flush=True)
                    direct.free()
                    direct = Pardiso(); globals()['_DIRECT'] = direct
                    continue
                print(f"    [linsolve] PARDISO failed ({type(e).__name__}: "
                      f"{str(e)[:60]}) -- falling back to AMG+CG for this run",
                      flush=True)
                direct.free(); direct = None
                if gsys is not None:
                    # AMG+CG needs the whole matrix and the device assembler emits
                    # only the upper triangle, so the host has to take over the
                    # assembly too.  Redo this iteration there rather than dying.
                    print("    [gpu] host assembly takes over (AMG needs the full "
                          "matrix)", flush=True)
                    gsys = None
                    opP.reuse = True
                    KAr = host_fixed_stiffness()
                    continue
        if direct is None:
            assert not upper, 'AMG needs the full matrix; host assembly should ' \
                              'have taken over when the direct solver was dropped'
            # Rebuild the hierarchy only every AMG_EVERY iterations (and whenever the
            # active set moves appreciably).  Setup is ~60-70% of the cost, so reuse is
            # the single biggest lever -- provided CG does not then grind.
            tsa = time.time()
            if ml is None or rebuild or (it % AMG_EVERY == 0):
                ml = make_amg(As, Brm*dg[:, None]); rebuild = False
            t_setup = time.time()-tsa
            xs, info = cg(As, bs, rtol=RTOL, maxiter=CG_MAX,
                          x0=(None if x0 is None else x0*dg),
                          M=ml.aspreconditioner(cycle='V'),
                          callback=lambda xk: nit.__setitem__(0, nit[0]+1))
            res = np.linalg.norm(bs - As@xs)/max(np.linalg.norm(bs), 1e-30)
            if res > 1e-5:
                ml = make_amg(As, Brm*dg[:, None])
                xs, info = cg(As, bs, rtol=RTOL, maxiter=CG_MAX,
                              M=ml.aspreconditioner(cycle='V'))
                res = np.linalg.norm(bs - As@xs)/max(np.linalg.norm(bs), 1e-30)
            tag_lin = 'amg'
        t_cg = time.time()-ts-t_setup
        x = xs/dg
        x0 = x
        eps_dev = None
        if gsys is not None:
            u, eps_dev, E_dev = gsys.pdl_update(x, spec.PDL_E1, spec.PDL_E2,
                                                spec.PDL_EPS_KNEE)
        else:
            u = P @ x

        rel = np.einsum('nij,nj->ni', R, u[dofs])
        cn = gref + np.einsum('ni,ni->n', nrm, rel)
        lam_new = np.where(cn < 0, -K_N*cn, 0.0)
        lam = lam_new if it == 0 else (1-RELAX)*lam + RELAX*lam_new
        new_active = cn < 0
        tang = rel - np.einsum('ni,ni->n', rel, nrm)[:, None]*nrm
        tmag_prev = (1-RELAX)*tmag_prev + RELAX*np.linalg.norm(tang, axis=1)

        if gsys is not None:
            E_new = E_dev.cpu().numpy()
        else:
            eps = opP.strain(u)
            E_new = pdl_secant_modulus(vm_equiv_strain(eps))
        E_new = E_new*pdl_scale
        adE = np.abs(E_new-E_pdl)
        dE = np.percentile(adE, 99.9)/spec.PDL_E2
        dE_max = adE.max()/spec.PDL_E2
        E_pdl = 0.5*E_pdl + 0.5*E_new

        Fc = float(np.linalg.norm((lam_new[:, None]*nrm).sum(0)))
        # p99.9, not the maximum.  Both of these are norms over 243k dofs / 168k
        # elements, and the maximum is pinned by a handful of marginal entities --
        # free aligner nodes, and elements straddling the 7.5% bilinear knee that
        # flip branch every iteration.  They held du at 1.4e-3 against a 1e-3
        # tolerance while the active set was frozen and the contact force was
        # constant to 1e-8, i.e. long after the solve was physically converged.
        # Same reason FINDINGS 5 reports p99 strain rather than the maximum.
        # The maxima are still recorded, as du_max / dE_max.
        adu = np.abs(u-u_prev) if u_prev is not None else None
        uscale = max(np.abs(u).max(), 1e-30)
        du = (np.percentile(adu, 99.9)/uscale) if u_prev is not None else 1.0
        du_max = (adu.max()/uscale) if u_prev is not None else 1.0
        dF = (abs(Fc-Fc_prev)/max(Fc, 1e-30)) if Fc_prev is not None else 1.0
        u_prev = u.copy(); Fc_prev = Fc
        if tc is not None:
            dt_ = Ct @ x
            tc_same = np.abs(dt_ - dlt_t).max() < 2e-5
            dlt_t = dt_
        dA = int((new_active != active).sum())
        hist.append(dict(it=it, active=int(new_active.sum()), dA=dA, cg=nit[0],
                         Fc=Fc, du=float(du), dF=float(dF), dE=float(dE),
                         du_max=float(du_max), dE_max=float(dE_max)))
        if verbose:
            print(f"    it{it:2d} act={new_active.sum():5d} dA={dA:4d} cg={nit[0]:4d} "
                  f"|Fc|={Fc:7.4f}N du={du:.2e} dF={dF:.2e} dE={dE:.2e} "
                  f"umax={np.abs(u).max()*1e3:7.2f}um  "
                  f"[{tag_lin} {t_setup+t_cg:4.1f}s res {res:.1e}]", flush=True)
        active = new_active
        if du < U_TOL and dF < F_TOL and dE < 1e-2 and it >= 3 and tc_same:
            break

    # report the TRUE penalty force (unrelaxed, zero off the active set); the
    # relaxed array is an iteration device and retains decayed values on pairs
    # that have since separated.
    if gsys is not None and eps_dev is not None:
        eps = eps_dev.cpu().numpy()          # 8 MB, once per solve rather than per iteration
    lam_true = np.where(new_active, lam_new, 0.0)
    q = {u_: x[S.q_col[u_]:S.q_col[u_]+6] for u_ in S.keep}
    if cache is not None:
        cache.update(x0=x, active=active, lam=lam, tmag=tmag_prev, npair=npair,
                     E_pdl=E_pdl, pairing=pairing)
    out = dict(u=u, x=x, q=q, lam=lam_true, lam_relaxed=lam, active=active, nrm=nrm, C=C, hist=hist,
               E_pdl=E_pdl, eps=eps, opP=opP, P=P, nodes=nodes)
    if tc is not None:
        out['tooth_contact'] = dict(Fsum=float(tc.N_last.sum()),
                                    gap_min=float((np.array([c[1] for c in tc.cur]) + dlt_t).min()))
    return out
